services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartexpense-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=SmartExpense;Username=postgres;Password=${DB_PASSWORD}
      - MultipleActiveResultSets=true
      - JwtOptions__Secret=${JWT_SECRET}
      - JwtOptions__Issuer=SmartExpenseApi
      - JwtOptions__Audience=SmartExpenseClient
      - AdminUser__Email=${ADMIN_EMAIL}
      - AdminUser__Password=${ADMIN_PASSWORD}
      - AdminUser__FirstName=Admin
      - AdminUser__LastName=User
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:80
    depends_on:
      db:
        condition: service_healthy
      seq:
        condition: service_started
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: smartexpense-seq
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINUSERNAME: ${SEQ_USER}
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_PASS}
    ports:
      - "8081:80"
      - "5341:80"
    volumes:
      - seqdata:/data
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: smartexpense-db
    environment:
      POSTGRES_DB: SmartExpense
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - sqldata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  sqldata:
  seqdata:            